-- Insert team resources from CSV
-- Generated from Team Resources-Grid view.csv
--
-- NOTE: This file includes table creation. If the table already exists, 
-- you can skip to the INSERT statement below.
-- If you encounter RLS (Row Level Security) errors, you may need to:
-- 1. Use the service role key, OR
-- 2. Temporarily add an INSERT policy for authenticated users

-- Create resources table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.resources (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  primary_category TEXT NOT NULL,
  secondary_tags TEXT[] DEFAULT '{}',
  link TEXT NOT NULL,
  source TEXT,
  description TEXT,
  username TEXT,
  password TEXT,
  instructions TEXT,
  documentation TEXT,
  view_count INTEGER DEFAULT 0,
  last_viewed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Create indexes if they don't exist
CREATE INDEX IF NOT EXISTS idx_resources_primary_category ON public.resources(primary_category);
CREATE INDEX IF NOT EXISTS idx_resources_secondary_tags ON public.resources USING GIN(secondary_tags);
CREATE INDEX IF NOT EXISTS idx_resources_name ON public.resources(name);

-- Enable Row Level Security (if not already enabled)
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;

-- Add INSERT policy for authenticated users (if needed for one-time import)
-- You can drop this policy after importing if you don't want users to insert directly
DROP POLICY IF EXISTS "Anyone authenticated can insert resources" ON public.resources;
CREATE POLICY "Anyone authenticated can insert resources"
  ON public.resources FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Add SELECT policy if it doesn't exist
DROP POLICY IF EXISTS "Anyone authenticated can view resources" ON public.resources;
CREATE POLICY "Anyone authenticated can view resources"
  ON public.resources FOR SELECT
  USING (auth.role() = 'authenticated');

-- Insert team resources from CSV
INSERT INTO public.resources (name, primary_category, secondary_tags, link, source, description, username, password, instructions, documentation) VALUES

  ('Ad Age', 'Research & Insights', ARRAY['News', 'Insights', 'Marketing', 'Advertising', 'Media'], 'https://adage.com/', 'Ad Age', 'Ad Age provides news, analysis, and insights on marketing, advertising, and media trends for industry professionals.', 'publications@codeandtheory.com', '285Fulton', NULL, NULL),
  ('Adweek', 'Research & Insights', ARRAY['News', 'Advertising', 'Marketing', 'Media', 'Technology'], 'https://www.adweek.com/', 'Adweek', 'Adweek provides news, analysis, and insights on advertising, marketing, media, and technology trends for industry professionals.', 'publications@codeandtheory.com', '285Fulton!', NULL, NULL),
  ('Baymard Institute', 'Research & Insights', ARRAY['Insights', 'Market Research', 'Consumer Research', 'Insight Mining', 'Reference'], 'https://baymard.com/premium/self-sign-up?t=OEl5nBm1568d', 'Baymard Institute', 'Unable to generate description.', NULL, NULL, 'Register with your @codeandtheory.com email via provided signup link. Set a password.', NULL),
  ('Bloomberg', 'Research & Insights', ARRAY['News', 'Business', 'Markets', 'Industry', 'Insight Mining'], 'https://www.bloomberg.com/', 'Bloomberg', 'Unable to generate description.', 'publications@codeandtheory.com', '285Fulton!', NULL, NULL),
  ('Business Insider', 'Research & Insights', ARRAY['News', 'Business', 'Finance', 'Markets', 'Insights'], 'https://www.businessinsider.com/', 'Business Insider', 'Business Insider provides news, analysis, and insights on business, finance, technology, and global markets.', 'publications@codeandtheory.com', '285Fulton', NULL, NULL),
  ('Business of Fashion', 'Research & Insights', ARRAY['News', 'Industry', 'Fashion', 'Trends', 'Insights'], 'https://www.businessoffashion.com/', 'BoF', 'Business of Fashion (BoF) provides news, analysis, and insights on the global fashion industry, covering trends, business strategies, and key industry developments.', 'publications@codeandtheory.com', '285Fulton!', NULL, NULL),
  ('Digiday', 'Research & Insights', ARRAY['Insights', 'Industry', 'Marketing', 'Media', 'Industry Trends'], 'https://digiday.com/', 'Digiday', 'Unable to generate description.', 'press@codeandtheory.com', '285Fulton!', NULL, NULL),
  ('Harvard Business Review', 'Research & Insights', ARRAY['Insights', 'Thought Leadership', 'Business', 'Management', 'Strategy'], 'https://hbr.org/', 'HBR', 'Harvard Business Review (HBR) offers expert insights, research, and analysis on business strategy, leadership, and management trends for professionals and organizations.', 'publications@codeandtheory.com', '285Fulton!', NULL, NULL),
  ('Insider Intelligence (eMarketer)', 'Research & Insights', ARRAY['Insights', 'Market Research', 'Consumer Research', 'Industry Trends', 'Marketing'], 'https://totalaccess.emarketer.com/Extranet.aspx?codeandtheory', 'Insider Intelligence / eMarketer', 'Unable to generate description.', NULL, NULL, 'Create your login via the link using your @codeandtheory.com email address.', NULL),
  ('LA Times', 'Research & Insights', ARRAY['News', 'Journalism', 'Insight Mining', 'Reference', 'Trends'], 'https://www.latimes.com/', 'Los Angeles Times', 'Unable to generate description.', 'publications@codeandtheory.com', '285Fulton', NULL, NULL),
  ('Mintel', 'Research & Insights', ARRAY['Insights', 'Market Research', 'Consumer Research', 'Industry Trends', 'Insight Mining'], 'https://portal.mintel.com/portal/login', 'Mintel', 'Unable to generate description.', NULL, NULL, 'Register with your @codeandtheory.com email. Click ''Validate'' in email. Complete form.', NULL),
  ('New York Times', 'Research & Insights', ARRAY['News', 'Journalism', 'Insights', 'Reference', 'Trends'], 'https://www.nytimes.com/', 'New York Times', 'Unable to generate description.', 'publications@codeandtheory.com', '285Fulton', NULL, NULL),
  ('The Drum', 'Research & Insights', ARRAY['News', 'Marketing', 'Advertising', 'Media', 'Industry Trends'], 'https://www.thedrum.com/', 'The Drum', 'The Drum is a global media platform covering marketing, advertising, and media industry news, trends, and insights.', 'nicole.santos@codeandtheory.com', 'CodeandTheory2021!', NULL, NULL),
  ('Wall Street Journal', 'Research & Insights', ARRAY['Insights', 'News', 'Business', 'Markets', 'Industry'], 'https://www.wsj.com/', 'WSJ', NULL, 'publications@codeandtheory.com', '285Fulton', NULL, NULL),
  ('Washington Post', 'Research & Insights', ARRAY['News', 'Journalism', 'Insight Mining', 'Reference', 'Trends'], 'https://www.washingtonpost.com/', 'Washington Post', NULL, 'publications@codeandtheory.com', '285Fulton', NULL, NULL),
  ('10 Examples of a Creative Brief', 'Communication & Presentation', ARRAY['Creative Brief', 'Advertising', 'Communication', 'Planning', 'Marketing'], 'https://docs.google.com/presentation/d/13fzyynoopKrGgj9tSpgXzhOXLtgfHgINNWG5GeSlOVc/edit#slide=id.g6495aec485_0_99', 'Planning Dirty', 'A collection of ten creative brief examples from various brands, illustrating effective ways to communicate project objectives and strategies in marketing and advertising.', NULL, NULL, NULL, NULL),
  ('Ad Campaign Boot Camp', 'Research & Insights', ARRAY['Insights', 'Advertising', 'Campaigns', 'Tool', 'Guide'], 'https://docs.google.com/document/d/17FHaADDER9aTf9Bv6UC0uN1DpTbZ-_jpzGDgqdaM-qk/edit', 'Gabriel Sehringer', 'A comprehensive guide by Gabriel Sehringer outlining strategies, tools, and best practices for running effective ad campaigns.', NULL, NULL, NULL, NULL),
  ('Assessing a Brief', 'Research & Insights', ARRAY['Insights', 'Insight Repository', 'Market Research', 'Consumer Research'], 'https://docs.google.com/document/d/1Q1zZJ1i_5U79AXeLc_gZaVuXA8DCP7qkEV8dU48e4gs/edit?usp=sharing', 'Internal (C&T)', 'Unable to generate description.', NULL, NULL, NULL, NULL),
  ('Baiba Matisone''s Decks (a library)', 'Research & Insights', ARRAY['Deck', 'Insights', 'Showcase', 'Insight Repository', 'Reference'], 'https://drive.google.com/drive/u/0/folders/1K0VrGRu6IQf62msG0CaAcnt3RxVOV2WB', 'Baiba Matisone', 'A collection of presentation decks curated by Baiba Matisone, serving as a library of her work and resources.', NULL, NULL, NULL, NULL),
  ('Better Questions for Better Ideas', 'Communication & Presentation', ARRAY['Planning', 'Strategy', 'Communication Planning', 'Insights', 'Creative Thinking'], 'https://docs.google.com/presentation/d/1k1Tf6NMbc7_hEFOiCxLatWzvA086pvGfk2mj312jwO4/edit?ct=t(Communication_Planning_Checklist11_17_2019_8_41)&mc_cid=c2a749421d&mc_eid=1a5a15638c#slide=id.g73e0f88637_0_195', 'Planning Dirty', 'This presentation from Planning Dirty explores how asking more effective questions can lead to stronger, more innovative ideas in planning and strategy.', NULL, NULL, NULL, NULL),
  ('Brainstorming Bible', 'Communication & Presentation', ARRAY['Brainstorming', 'Creative Thinking', 'Frameworks', 'Strategy', 'Planning'], 'https://docs.google.com/presentation/d/1CkRIrIAJTEqwcA-pkv8TXuyac8EaK0C8q06NYu8-D2M/edit', 'Planning Dirty', 'A presentation from Planning Dirty offering strategies, frameworks, and tips to enhance brainstorming sessions and generate creative ideas effectively.', NULL, NULL, NULL, NULL),
  ('Challenger Brand Narratives', 'Strategy & Planning', ARRAY['Challenger Brands', 'Narrative', 'Brand Strategy', 'Strategy', 'Narratives'], 'https://thechallengerproject.com/blog/2015/challenger-brand-narratives', 'The Challenger Project', 'An exploration of how challenger brands use distinctive narratives to differentiate themselves and disrupt established market leaders.', NULL, NULL, NULL, NULL),
  ('ChatGPT', 'Learning & Technology', ARRAY['AI', 'Assistive', 'Tool', 'Technology', 'Internal Tool'], 'https://chat.openai.com/', 'OpenAI / Internal Use', 'ChatGPT is an AI-powered conversational tool developed by OpenAI, designed to assist users with information, tasks, and creative prompts through natural language interactions.', NULL, NULL, NULL, NULL),
  ('Comms Planning Stats', 'Communication & Presentation', ARRAY['Communication Planning', 'Insights', 'Planning', 'Strategy', 'Trends'], 'https://docs.google.com/presentation/d/1ibvDiw7EoP5SFnxlJXHyMEV76enZhFXpkjjiR7md6k0/edit#slide=id.g64e16436a2_0_287', 'Planning Dirty', 'An overview of key statistics and data points relevant to communications planning, highlighting trends and insights for effective strategy development.', NULL, NULL, NULL, NULL),
  ('Courses for Strategists', 'Research & Insights', ARRAY['Reading List', 'Insight Repository', 'Strategy', 'Reference', 'Early-Career Learning'], 'https://docs.google.com/spreadsheets/d/1tJPrpNeJyaXST2XEGsWKAMhBS0wGsQaq7teISAJaW2o/edit#gid=0', 'Stephen Brooks', 'A curated spreadsheet by Stephen Brooks listing recommended courses and resources for strategists to enhance their skills and knowledge.', NULL, NULL, NULL, NULL),
  ('Deck of Brilliance', 'Creative & Inspiration', ARRAY['Creative Prompts', 'Ideation', 'Creative Thinking', 'Tool', 'Inspiration'], 'https://deckofbrilliance.com/', 'Juggi Ramakrishnan and Todd McCracken', 'Deck of Brilliance is a creative tool by Juggi Ramakrishnan and Todd McCracken that offers a collection of prompts and exercises designed to spark innovative thinking and idea generation.', NULL, NULL, NULL, NULL),
  ('Defining the Insight', 'Communication & Presentation', ARRAY['Insights', 'Strategy', 'Deck', 'Communication', 'Thought Leadership'], 'https://docs.google.com/presentation/d/1GYNRD_jQ-05_RVB76mV9EN4wjUW3PCtVB3GgbU4Ybzg/edit', 'Mark Pollard', 'Mark Pollard''s "Defining the Insight" presentation explores how to identify and articulate meaningful insights to drive effective strategy and creative work.', NULL, NULL, NULL, NULL),
  ('Discovery Questions', 'Communication & Presentation', ARRAY['Planning', 'Guide', 'Communication Planning', 'Workshop', 'Strategic Thinking'], 'https://docs.google.com/presentation/d/1ZUmXSM7drf-z8uLRUepH5_UYCBEZ_b7b4Ko-DOu1hBc/edit#slide=id.g61807bb1cd_1_0', 'Planning Dirty', 'A guide from Planning Dirty outlining key discovery questions to uncover client needs and objectives during the planning process.', NULL, NULL, NULL, NULL),
  ('Dovetail', 'Research & Insights', ARRAY['Insight Repository', 'Consumer Research', 'Tool', 'Market Research', 'Insight Mining'], 'http://dovetailapp.com', 'Dovetail', 'Dovetail is a platform that helps teams organize, analyze, and share customer research and insights to improve decision-making and product development.', NULL, NULL, NULL, NULL),
  ('Elvex', 'Learning & Technology', ARRAY['AI', 'Tool', 'Assistive', 'Internal Tool', 'Technology'], 'https://elvex.ai', 'Elvex / Internal Platform', 'Elvex is an internal platform designed to streamline workflows and enhance productivity through AI-driven solutions.', NULL, NULL, NULL, NULL),
  ('Essential Strategy Books by Women', 'Research & Insights', ARRAY['Reading List', 'Insights', 'Strategy', 'Thought Leadership', 'Reference'], 'https://docs.google.com/document/d/1kI6QWtrgth8Yp2RFR3oCjpZEYESnh9n9Re_fYjBusqk/edit#heading=h.nemgyvya6npb', 'Current Forward', 'A curated list of influential strategy books authored by women, highlighting their unique perspectives and contributions to the field.', NULL, NULL, NULL, NULL),
  ('Framework Factory', 'Communication & Presentation', ARRAY['Frameworks', 'Strategy', 'Planning', 'Tool', 'Campaign Planning'], 'https://docs.google.com/presentation/d/1oI91JTOIk4uZ36aXCCBWiSpYWFnSndQO5RRN8Txg2bc/edit#slide=id.g5608b64f64_0_322', 'Planning Dirty', 'Framework Factory by Planning Dirty presents a collection of strategic frameworks and tools designed to help marketers and planners structure their thinking and improve campaign planning.', NULL, NULL, NULL, NULL),
  ('Free Online Research Tools', 'Research & Insights', ARRAY['Tool', 'Insight Repository', 'Reference', 'Spreadsheet', 'Insights'], 'https://docs.google.com/spreadsheets/d/1sylVPS6Q5wP22sBG5zGedWmvf6rS86Vb_8mrnir2NaA/edit#gid=891834841', 'Maria Parisi', 'A curated list of free online research tools compiled by Maria Parisi, offering resources to support various research needs.', NULL, NULL, NULL, NULL),
  ('Good Questions', 'Research & Insights', ARRAY['Insights', 'Insight Repository', 'Market Research', 'Consumer Research'], 'https://docs.google.com/document/d/14dWAZ2um_5bWS80K09F_HstWVTL_XIZdxBV9gnzfyIk/edit', 'Internal (C&T)', 'Unable to generate description.', NULL, NULL, NULL, NULL),
  ('Heidi Heckermeyer Strategy YouTube', 'Research & Insights', ARRAY['Strategy', 'Insights', 'Thought Leadership', 'Business', 'Management'], 'https://www.youtube.com/channel/UCdaBXEptHSk5UYkJzZwrZbA/videos', 'Heidi Hackemeyer', 'Heidi Heckermeyer Strategy YouTube features videos by Heidi Hackemeyer focused on business strategy, leadership, and professional development insights.', NULL, NULL, NULL, NULL),
  ('How To Find Stuff', 'Communication & Presentation', ARRAY['Guide', 'Communication', 'Insights', 'Strategy', 'Reference'], 'https://docs.google.com/presentation/d/e/2PACX-1vRZkVTyjlQb2soJiJ8-bArUnmHhBHDRoSWmMjwhPZzfdw8-mqCglc9cZScEyWO7-4hRWzMx-lQn1tB1/pub?start=false&loop=false&delayms=60000&slide=id.gfd70b8e073_0_0', 'Francisca Pelligrini', 'A guide by Francisca Pelligrini outlining effective strategies and tips for finding information and resources efficiently.', NULL, NULL, NULL, NULL),
  ('Hunter’s Guide to BS-Free Insights', 'Research & Insights', ARRAY['Insights', 'Guide', 'Insight Mining', 'Marketing', 'Advertising'], 'https://www.slideshare.net/tommorton/a-hunters-guide-to-bsfree-insights/', 'Tom Morton / SlideShare', 'A practical guide by Tom Morton on identifying and generating genuine, actionable insights in marketing, avoiding common pitfalls and superficial analysis.', NULL, NULL, NULL, NULL),
  ('Ice Breaker Wiki', 'Research & Insights', ARRAY['Activity', 'Workshop', 'Team Communication', 'Work Culture', 'Inspiration'], 'https://docs.google.com/document/d/1npWZ6ln0GjT4Vup05_a3djPSEoS-_NNfQOYVSRMnaUM/edit#heading=h.hoeltmnem2za', 'Internal (C&T)', 'A collaborative internal wiki providing ice breaker activities and ideas for team engagement and relationship building within C&T.', NULL, NULL, NULL, NULL),
  ('IDEOU: 10 Activities to Generate Better Ideas', 'Creative & Inspiration', ARRAY['Activity', 'Creative Thinking', 'Ideation', 'Inspiration', 'Brainstorming'], 'https://www.ideou.com/blogs/inspiration/10-activities-to-generate-better-ideas', 'IDEOU', 'This article from IDEOU outlines ten practical activities designed to spark creativity and help individuals or teams generate more effective and innovative ideas.', NULL, NULL, NULL, NULL),
  ('Junior Strategy Resource Hub', 'Strategy & Planning', ARRAY['Strategy', 'Planning', 'Guide', 'Tools', 'Early-Career Learning'], 'http://www.juniorstrategy.com/', 'Youngbloods Australia', 'A comprehensive resource hub by Youngbloods Australia offering guides, tools, and advice for junior strategists in the advertising and marketing industry.', NULL, NULL, NULL, NULL),
  ('Love the Work More (2022)', 'Creative & Inspiration', ARRAY['Showcase', 'Award-Winning Creative', 'Advertising Examples', 'Inspiration', 'Industry Trends'], 'https://lovetheworkmore.com/2022-2/', 'Internal (C&T)', 'A showcase of standout advertising campaigns and creative work from 2022, highlighting innovative ideas and industry trends.', NULL, NULL, NULL, NULL),
  ('Midjourney', 'Creative & Inspiration', ARRAY['AI', 'Visual Ideation', 'Inspiration', 'Creative Prompts', 'Tools'], 'https://www.midjourney.com/', 'Midjourney / Internal Use', 'Midjourney is an AI-powered platform that generates images from text prompts, enabling users to create unique visual content through artificial intelligence.', NULL, NULL, NULL, NULL),
  ('MURAL: Remote Ideation Techniques', 'Creative & Inspiration', ARRAY['Remote Facilitation', 'Ideation', 'Creative Thinking', 'Workshop', 'Activity'], 'https://www.mural.co/blog/remote-ideation-techniques', 'MURAL', 'Explore effective techniques and best practices for facilitating ideation sessions remotely, helping teams generate creative ideas and collaborate virtually using MURAL.', NULL, NULL, NULL, NULL),
  ('Nockwood Cards', 'Tools & Templates', ARRAY['Tools', 'Inspiration', 'Creative Industry', 'Showcase'], 'https://www.nockwoodcards.com/buy/NOCKWOOD-CARDS-c18195021', 'Nockwood Cards', 'Nockwood Cards offers a selection of unique, handcrafted wooden greeting cards for various occasions, available for purchase online.', NULL, NULL, NULL, NULL),
  ('Phoenix Checklist', 'Research & Insights', ARRAY['Checklist', 'Creative Thinking', 'Insights', 'Tool', 'Strategic Thinking'], 'https://docs.google.com/document/d/1wt2VRywNQGM7ciu9PxR8TEJF7m7NyhQtkW0JMFwlK04/edit', 'Internal (C&T)', 'The Phoenix Checklist is an internal C&T document providing a series of structured questions designed to guide problem-solving and critical thinking processes.', NULL, NULL, NULL, NULL),
  ('Politics 101', 'Communication & Presentation', ARRAY['Deck', 'Planning', 'Communication', 'Strategy', 'Guide'], 'https://docs.google.com/presentation/d/1xz5DcaGUYYZbA3qkZyenKa61nMK5UK3dTW2RbAk1gN4/edit#slide=id.g5e1f842b36_1_403', 'Planning Dirty', 'An introductory presentation from Planning Dirty outlining the basics of politics, including key concepts and strategies for understanding political systems.', NULL, NULL, NULL, NULL),
  ('Roger Martin – What Makes a Great Strategist', 'Strategy & Planning', ARRAY['Strategy', 'Strategic Thinking', 'Thought Leadership', 'Insights', 'Strategy Theory'], 'https://rogermartin.medium.com/what-makes-for-a-great-strategist-abf89e1408f2', 'DeckOfBrilliance.com', 'Roger Martin explores the essential qualities and mindsets that distinguish exceptional strategists, emphasizing critical thinking, curiosity, and the ability to embrace complexity.', NULL, NULL, NULL, NULL),
  ('Sean''s Cultural Moments', 'Research & Insights', ARRAY['Insights', 'Culture', 'Spreadsheet', 'Reference', 'Insight Repository'], 'https://docs.google.com/spreadsheets/d/1iq7BsIRJEaFVxusbxq1wbB8C3SbPBm0Bc8blTqZP80U/edit#gid=1515490672', 'Sean', 'A curated spreadsheet by Sean highlighting significant cultural events and moments.', NULL, NULL, NULL, NULL),
  ('Strategy 101 Toolkit', 'Research & Insights', ARRAY['Strategy', 'Frameworks', 'Guide', 'Insights', 'Tool'], 'https://docs.google.com/document/d/1ax_EjpUfOMBG5qVbj9BUabs7RMiw0CoxYT2jNB5j7oM/edit', 'John Simons', 'A practical guide by John Simons offering essential tools and frameworks for developing and implementing effective business strategies.', NULL, NULL, NULL, NULL),
  ('Strategy and Planning Scrapbook', 'Strategy & Planning', ARRAY['Strategy', 'Planning', 'Frameworks', 'Insights', 'Strategic Thinking'], 'https://view.publitas.com/thechopshop/theory-of-strategy-and-planning/page/1', 'Publitas', 'A curated collection of insights and resources on strategy and planning, offering practical frameworks and ideas for effective organizational decision-making.', NULL, NULL, NULL, NULL),
  ('Strategy Blank Checks', 'Communication & Presentation', ARRAY['Strategy', 'Frameworks', 'Planning', 'Deck', 'Guide'], 'https://docs.google.com/presentation/d/1_nNLV3kdgmrfgxxFRMZq1AXcV2N8tGBz1Uq-uK1KJFw/edit#slide=id.g7ddd3f40ce_0_340', 'Planning Dirty', 'An overview of the "Strategy Blank Checks" framework from Planning Dirty, providing templates and guidance for developing strategic plans.', NULL, NULL, NULL, NULL),
  ('Strategy Finishing School Cheatsheet Data Sources 2022', 'Research & Insights', ARRAY['Insights', 'Planning', 'Reference', 'Market Research', 'Insight Repository'], 'https://docs.google.com/spreadsheets/d/1M2hvkIaRSVnIu88L4nC8g1q8OU8LWI8Oe6VXi_mdbH0/edit#gid=2145591817', 'Planning Dirty', 'A comprehensive cheatsheet from Planning Dirty listing key data sources for strategy professionals in 2022, aiding in research and planning efforts.', NULL, NULL, NULL, NULL),
  ('Strategy Needs Good Words – Martin Weigel', 'Strategy & Planning', ARRAY['Strategy', 'Writing', 'Strategic Writing', 'Language', 'Communication'], 'https://www.martinweigel.org/blog/2019/03/20/strategy-needs-good-wordshttps://www.martinweigel.org/mrweigelgmailcom/2019/03/20/strategy-needs-good-words', 'Martin Weigel', 'Martin Weigel argues that clear, precise language is essential for effective strategy, emphasizing that good words help communicate and realize strategic ideas.', NULL, NULL, NULL, NULL),
  ('Strategy Slack Groups', 'Research & Insights', ARRAY['Insights', 'Strategy', 'Communication', 'Work Culture', 'Inspiration'], 'https://www.linkedin.com/posts/baiba-matisone_slack-activity-6770222503206952960-LA4_?utm_source=share&utm_medium=member_desktop', 'LinkedIn', 'A LinkedIn post discussing the value and benefits of participating in Slack groups focused on strategy, highlighting opportunities for networking and knowledge sharing.', NULL, NULL, NULL, NULL),
  ('Strategy Starter Pack', 'Research & Insights', ARRAY['Guide', 'Frameworks', 'Strategy', 'Insights', 'Tool'], 'https://docs.google.com/document/d/1E57VmpKcqmIiyplgs2r9zTDSkfz0dKnSo-oZwWpe5w0/edit', 'Jay Emsey', 'A practical guide by Jay Emsey offering foundational tools and frameworks to help individuals and teams develop effective business strategies.', NULL, NULL, NULL, NULL),
  ('Stratetgy Scrapbook', 'Communication & Presentation', ARRAY['Strategy', 'Frameworks', 'Planning', 'Insights', 'Marketing'], 'https://docs.google.com/presentation/d/1TTM5MZQPaaV6qvFMSP0llTD33dzCVyBQfb3rIFgayBg/edit', 'Planning Dirty', 'A collection of strategic planning insights and frameworks curated by Planning Dirty to inspire and guide effective marketing strategies.', NULL, NULL, NULL, NULL),
  ('Structure Your Presentation Like a Story (HBR)', 'Communication & Presentation', ARRAY['Storytelling', 'Communication', 'Narrative', 'Strategic Messaging'], 'https://hbr.org/2012/10/structure-your-presentation-li', 'Harvard Business Review', 'This article from Harvard Business Review explains how structuring presentations like stories can engage audiences and make messages more memorable and impactful.', NULL, NULL, NULL, NULL),
  ('The Drum: World’s Best Ads', 'Creative & Inspiration', ARRAY['Award-Winning Creative', 'Showcase', 'Advertising Examples', 'Inspiration', 'Creative Industry'], 'https://www.thedrum.com/the-worlds-best-ads-all-time', 'The Drum', 'A curated showcase by The Drum highlighting some of the most creative and impactful advertisements from around the world, celebrating excellence in advertising.', NULL, NULL, NULL, NULL),
  ('The Greatest Sales Deck I’ve Ever Seen', 'Communication & Presentation', ARRAY['Deck', 'Communication', 'Slides', 'Storytelling', 'Sales Storytelling'], 'https://medium.com/the-mission/the-greatest-sales-deck-ive-ever-seen-4f4ef3391ba0', 'Andy Raskin / Medium', 'Andy Raskin analyzes a highly effective sales deck, breaking down its structure and key elements that make it persuasive and successful in winning customers.', NULL, NULL, NULL, NULL),
  ('What is an Insight?', 'Communication & Presentation', ARRAY['Insights', 'Communication', 'Strategy', 'Consumer Research'], 'https://docs.google.com/presentation/d/1jZ3LkTxnbpaCgKF6HhYGjTATxpUimRYPYDLoe79yFPY/edit#slide=id.g1234ba14308_0_25', 'Charlotte Cramer', 'This presentation by Charlotte Cramer explains the concept of an "insight," detailing its definition and importance in understanding consumer behavior and driving effective strategies.', NULL, NULL, NULL, NULL)
;
